name: bundlemon

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
      - run: bun --version
      - run: bun install --frozen-lockfile
      - run: bun run build
      - name: bundlemon
        uses: lironer/bundlemon-action@322b592fa74951c6932a5f2858d64e83c22a9186 # v1
