name: bundlemon

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
      - run: bun --version
      - run: bun install --frozen-lockfile
      - run: bun run build
      - name: bundlemon
        uses: lironer/bundlemon-action@4233dd2af9eb1b13d5fa41bde6511db4041b6420 # v1
